### ISSUE TITLE
Warning: Invalid argument supplied to oneOfType. Expected an array of check functions, but received an object at index 4.

### ISSUE THREAD

**Issue by Ahmed-ab96** [fawaz-ahmed/react-native-read-more#11]
It works fine, but show this warning
![1](https://user-images.githubusercontent.com/31816755/97963063-75623580-1dc7-11eb-8fe8-264043c525b1.PNG)

**Comment by fawaz-ahmed** [comment]
> It works fine, but show this warning
> ![1](https://user-images.githubusercontent.com/31816755/97963063-75623580-1dc7-11eb-8fe8-264043c525b1.PNG)

Can you please share what props and data are you passing ?

**Comment by Ahmed-ab96** [comment]
Here is my code
```
<ReadMore
      seeMoreText='زیاتر'
      seeMoreStyle={{fontFamily:'Speda',color:'crimson'}}
      seeLessText='کەمتر'
      seeLessStyle={{fontFamily:'Speda',color:'crimson'}}
      numberOfLines={3}
     >
    <Text style={[HomeStyle.SecondaryText,{textAlign:'auto'}]}>{Item.Description}</Text>
</ReadMore>
```

and only by importing ReadMore without using it, that warning will appear.

**Comment by fawaz-ahmed** [comment]
> Here is my code
> 
> ```
> <ReadMore
>       seeMoreText='زیاتر'
>       seeMoreStyle={{fontFamily:'Speda',color:'crimson'}}
>       seeLessText='کەمتر'
>       seeLessStyle={{fontFamily:'Speda',color:'crimson'}}
>       numberOfLines={3}
>      >
>     <Text style={[HomeStyle.SecondaryText,{textAlign:'auto'}]}>{Item.Description}</Text>
> </ReadMore>
> ```
> 
> and only by importing ReadMore without using it, that warning will appear.

Resolved issue with [PR](https://github.com/fawaz-ahmed/react-native-read-more/pull/13)

Please upgrade to version 1.0.9
