### ISSUE TITLE
Show more always shown

### ISSUE THREAD

**Issue by IbrahimCanKALYA** [fawaz-ahmed/react-native-read-more#17]
on ios everything seems fine but on android;
always show more button showing..

**Comment by fawaz-ahmed** [comment]
@IbrahimCanKALYA can you share some more info like screenshot and some piece of code on how you're using it ?
This can help me fix.

**Comment by IbrahimCanKALYA** [comment]
![image](https://user-images.githubusercontent.com/33005883/105422873-8d728400-5c55-11eb-8bc9-769831ce8b77.png)

![image](https://user-images.githubusercontent.com/33005883/105422939-a8dd8f00-5c55-11eb-91f1-92d4a1d1ee02.png)



```

 <ReadMore
      style={{...styles.defaultTextStyle, ...style}}
      numberOfLines={numberOfLines}
      allowFontScaling={false}
      seeMoreText="more"
      seeLessText="less"
      seeMoreStyle={{...style, ...styles.seeMoreLessStyle, ...seeMoreStyle}}
      seeLessStyle={{...style, ...styles.seeMoreLessStyle, ...seeLessStyle}}
      {...props}>
      {renderText()}
    </ReadMore>
```


i'm facing with this issue on samsung s20

**Comment by IbrahimCanKALYA** [comment]
i find the problem where he is. when i set allowFontScaling={false} this problem accoures but i need to set this parameter

i fixed this issue via this usage:
```

customTextComponent={(props: TextProps) => (
        <Text {...props} allowFontScaling={false} />
      )}
```

**Comment by fawaz-ahmed** [comment]
@IbrahimCanKALYA thanks for providing more info. I've fixed this issue. Now just passing `allowFontScaling={false}` should be sufficient and you can remove `customTextComponent`.
Upgrade to version ^1.1.4
