### ISSUE TITLE
Some forgotten console.log I think

### ISSUE THREAD

**Issue by S2LF** [fawaz-ahmed/react-native-read-more#24]
Hi ! 

Nice package, helps me a lot in my student project !!

There are some console.log which are displayed when <ReadMore> component are mount.

Not really an issue just maybe an esthetic issue when I'm tring to debug.

![image](https://user-images.githubusercontent.com/49229770/111367063-9c454800-8694-11eb-9741-ca93fb7ac29f.png)

Hope it can help.
S2LF

**Comment by fawaz-ahmed** [comment]
Hi S2LF,
Well this is very encouraging for me to continue over this module. Thanks for pointing this out. I'll release a fix for this within the next few days.
Cheers,

________________________________
From: S2LF ***@***.***>
Sent: Wednesday, March 17, 2021, 12:22 AM
To: fawaz-ahmed/react-native-read-more
Cc: Subscribed
Subject: [fawaz-ahmed/react-native-read-more] Some forgotten console.log I think (#24)


Hi !

Nice package, helps me a lot in my student project !!

There are some console.log which are displayed when component are mount.

Not really an issue just maybe an esthetic issue when I'm tring to debug.

[image]<https://user-images.githubusercontent.com/49229770/111367063-9c454800-8694-11eb-9741-ca93fb7ac29f.png>

Hope it can help.
S2LF
