### ISSUE TITLE
Can We use HTML content inside in this Library

### ISSUE THREAD

**Issue by XamBoy** [fawaz-ahmed/react-native-read-more#25]

**Comment by fawaz-ahmed** [comment]
@XamBoy It hasn't been tested with html content and I'm afraid it won't support html out of the box. You can pass any html renderer as a custom component and check if that works.
Another fix would be to rip off tags from tags from html and pass the bare text to this component, as mentioned [here](https://stackoverflow.com/questions/29334984/render-html-in-react-native)

**Comment by fawaz-ahmed** [comment]
Html is not compatible. Closing issue
