### ISSUE TITLE
Flickering "See more" text on first render on Android.

### ISSUE THREAD

**Issue by sukanyaevon** [fawaz-ahmed/react-native-read-more#28]
On iOS it is working fine but on Android when the page loads for the first time, the "See more" text flickers i.e first the text is shown and then "See more" and "ellipsis" shows.
Using react-native latest version 0.63.
```
<ReadMore
          seeMoreStyle={styles.readMoreContainer}
          numberOfLines={3}
          expandOnly={true}
          style={ styles.message}
          allowFontScaling={false}
          debounceSeeMoreCalc={0}
          animate={false}
        >
```

**Comment by fawaz-ahmed** [comment]
I'll have a look @jeon9878
________________________________
From: jeon9878 ***@***.***>
Sent: Tuesday, April 13, 2021 11:37:17 AM
To: fawaz-ahmed/react-native-read-more ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [fawaz-ahmed/react-native-read-more] Flickering "See more" text on first render on Android. (#28)


On iOS it is working fine but on Android when the page loads for the first time, the "See more" text flickers i.e first the text is shown and then "See more" and "ellipsis" shows.
Using react-native latest version 0.63.

<ReadMore
          seeMoreStyle={styles.readMoreContainer}
          numberOfLines={3}
          expandOnly={true}
          style={ styles.message}
          allowFontScaling={false}
          debounceSeeMoreCalc={0}
          animate={false}

**Comment by sukanyaevon** [comment]
I tried it with setting `animate={false}` and `debounceSeeMoreCalc={0}`  but still Android seems not to work properly. 
Please solution asap

**Comment by fawaz-ahmed** [comment]
@jeon9878 since it takes 2 renders to complete the calculation on where to position see more therefore you see it later. For the flicker can you share a video ?
Also have you tried setting up the prop
preserveLinebreaks={true}
________________________________

**Comment by sukanyaevon** [comment]
Yes tried this preserveLinebreaks={true} but still not succeded. Here is the video 
https://user-images.githubusercontent.com/35032724/114513299-ab012980-9c57-11eb-8e47-958ca1a688e6.mov
_since it takes 2 renders to complete the calculation on where to position see more therefore you see it later._
Quick solutions for this?

**Comment by fawaz-ahmed** [comment]
@jeon9878 Use version `1.1.5` and make sure to supply prop `backgroundColor` if anything other than `white`
Thanks for sharing the video, I can see the flicker. It should render show more in the correct place rather moving in from the corner. I will take that up!

**Comment by sukanyaevon** [comment]
@fawaz-ahmed the flickering effect is not happening on version 1.1.5 (y) .
However the show more view size is cropping the text now. The backgroundColor is white only. Please suggest
![Screenshot 2021-04-13 at 2 25 05 PM](https://user-images.githubusercontent.com/35032724/114526058-45676a00-9c64-11eb-8836-c548facf2bb4.png)

**Comment by fawaz-ahmed** [comment]
@jeon9878 set prop `allowFontScaling={false}` it's a known issue with android also mentioned [here](https://github.com/fawaz-ahmed/react-native-read-more#troubleshooting)
If this doesn't works, try passing the styles for see more, see prop `seeMoreStyle`

**Comment by sukanyaevon** [comment]
@fawaz-ahmed thanks for your quick solutions. It worked with some styling to `seeMoreStyle`. 
One more thing, i need to add underline style to show more text and I have added `textDecorationLine: 'underline'` to `seeMoreStyle` but the underline is showing below the ellipsis too. It should be only below the text.
A great library to use. Just this and it takes away all other

**Comment by fawaz-ahmed** [comment]
@jeon9878 no quick fix for this
________________________________

**Comment by sukanyaevon** [comment]
@fawaz-ahmed on latest version it is working however. Can you please provide how it is handled in latest version?

**Comment by fawaz-ahmed** [comment]
@jeon9878 you can refer to code. I won't be able to give you all the details here. I'll try to fix this asap but cant give you an estimate, maybe I'll do it around the weekend
________________________________

**Comment by sukanyaevon** [comment]
@fawaz-ahmed ok thank you (y)

**Comment by fawaz-ahmed** [comment]
@jeon9878 fix for this issue has been added, please upgrade to version 2.0.2
