### ISSUE TITLE
Custom See More component doesn't get adjusted based on the width of the container.

### ISSUE THREAD

**Issue by Karansidds** [fawaz-ahmed/react-native-read-more#34]
![Image from iOS](https://user-images.githubusercontent.com/39003188/125569707-353d51df-b852-40b7-80c6-e946d2e7141d.jpg)

**Description**
When I'm using a custom text for the See More button, it doesn't get adjusted if the width of the container is reduced. The text gets adjusted, but the See More button stays the same and overlaps with the text. I am assuming that the See More button should stay hidden if the container is small, instead of overlapping with the text. 

**Code**
```
<SafeAreaView style={rnStyles.safe}>
      <View style={rnStyles.root}>
        <ReadMore
          numberOfLines={lines}
          style={[styles.text, rnStyles.text]}
          seeMoreText={showButtonText}
          seeLessText={hideButtonText}
          seeMoreStyle={[styles.showButtonText, rnStyles.buttonSpacing]}
          seeLessStyle={[styles.hideButtonText, rnStyles.buttonSpacing]}
          animate={false}
          allowFontScaling={false}
          onExpand={handleActions}
        >
          {text}
       </ReadMore>
    </View>
</SafeAreaView>

// Styles
const rnStyles = StyleSheet.create({
  safe: {
    flex: 1,
  },
  root: {
    flex: 1,
  },
  text: {
    lineHeight: 20,
    marginRight: 5,
  },
  buttonSpacing: {
    marginLeft: 5,
  },
});
```
`styles.showButtonText`, `styles.hideButtonText` and `styles.text` are dynamic styles that contain `fontSize`, `color`, `fontWeight` and `fontFamily`.

**Comment by fawaz-ahmed** [comment]
@Karansidds thanks for pointing this out. What shall happen in this case ?
Should the see more text start appearing in next line ? please suggest

**Comment by fawaz-ahmed** [comment]
Closing this issue due to no response
