### ISSUE TITLE
SeeMore text cover on content text

### ISSUE THREAD

**Issue by truongqt** [fawaz-ahmed/react-native-read-more#40]
The "SeeMore" text cover on the Content if the width of the Content's View is about ~100 - 200

**Comment by fawaz-ahmed** [comment]
> The "SeeMore" text cover on the Content if the width of the Content's View is about ~100 - 200

@truongqt you can reduce the see more text based on your container width, use prop `seeMoreText`

**Comment by fawaz-ahmed** [comment]
@truongqt a bug was fixed related to measurements. You may want to upgrade to ver 2.2.2 and try if the issue persists. Incase it does, feel free to reopen the issue.
