### ISSUE TITLE
Not working on react-native version 0.65.1

### ISSUE THREAD

**Issue by ghost** [fawaz-ahmed/react-native-read-more#41]
the button read more/read less is not present

**Comment by fawaz-ahmed** [comment]
> the button read more/read less is not present

Hi @mantegnous can you please mention the react native version ?
Also please share the code snippet and screenshot ? Just to be sure everything is okay in the code.
Thanks for pointing this out.

**Comment by ghost** [comment]
> > the button read more/read less is not present
> 
> Hi @mantegnous can you please mention the react native version ? Also please share the code snippet and screenshot ? Just to be sure everything is okay in the code. Thanks for pointing this out.

 "react-native": "^0.65.1",
 
 I have update for use my app ith ios 15 and android 12, but, after this, the buttone is missed and the text is cutted
 
 `<ReadMore
      numberOfLines={3}
      style={styles.regular}
      seeMoreText={'Read more'}
      seeLessStyle={styles.readMore}
      seeMoreStyle={styles.readMore}
      seeLessText={'Read less'}>
      {children}
    </ReadMore>`
    
    
    children is a string that render my text as always

**Comment by ghost** [comment]
The issue is: line state is always 0 , cannot read the length of the text, something must have changed in native events

**Comment by ghost** [comment]
@fawaz-ahmed any news?

**Comment by fawaz-ahmed** [comment]
> @fawaz-ahmed any news?

@mantegnous I'm checking now. Will update in an hour or so.

**Comment by fawaz-ahmed** [comment]
@mantegnous I was able to reproduce the issue and also identify the cause. The fix will be rolled out in next hour

**Comment by ghost** [comment]
@fawaz-ahmed i have updated at last version, but the bug persist, i dont see the buttons to see more or see less, my text is cutted. version react nativie: 0.65.1

**Comment by fawaz-ahmed** [comment]
@mantegnous I tested with rn version `0.66.1`. Few things to check:
1_ Version for this package should be `2.2.0`. Make sure to check in `package-lock.json` file or `yarn.lock` file. If not remove package and re-install
2_ Run the example in this project (see README.md), tell me if this works fine or not ?
3_ Share a screenshot of what you are seeing ? it might be some other issue related to styling!

**Comment by ghost** [comment]
@fawaz-ahmed i tried with your example, and without any styles, but i see the text cutted, no label to collpse or extend, i'm in 2.2.0,  with react native 0.65.1,

**Comment by ghost** [comment]
@fawaz-ahmed in 0.66.1 work correctly, so.. the problem is below 0.66.1

**Comment by fawaz-ahmed** [comment]
@mantegnous in that case I would recommend you to upgrade your rn version to 0.66.1.

Also I'm attaching screenshots of my example for reference

**iOS collapsed**
![Simulator Screen Shot - iPhone 12 - 2021-10-19 at 18 07 12](https://user-images.githubusercontent.com/17975968/137916200-25250414-492c-4f75-9653-b5131a254f4d.png)

**iOS expanded**
![Simulator Screen Shot - iPhone 12 - 2021-10-19 at 18 07 17](https://user-images.githubusercontent.com/17975968/137916250-1483b0a1-b335-460a-b57f-d888b3eb54fe.png)

**android collapsed**
![Screenshot_1634648983](https://user-images.githubusercontent.com/17975968/137916325-ea0fa4e9-bd2d-49f6-bb06-8a1803c3eda8.png)

**android expanded**
![Screenshot_1634648989](https://user-images.githubusercontent.com/17975968/137916396-797ad312-be17-48dd-bf72-86c915d9b345.png)

**Comment by ghost** [comment]
@fawaz-ahmed ok i have updated my app, thanks for fix in 0.66.1 !
