### ISSUE TITLE
Couldn't find any versions for "react-native-read-more" that matches "^2.2.0"

### ISSUE THREAD

**Issue by fantasyado** [fawaz-ahmed/react-native-read-more#43]
I  see the latest version is 2.2.0 on npm but when running yarn it only fetches the v1.0.0 and displays the following info.
I have no idea what's wrong here.

yarn install v1.22.4
[1/4] 🔍  Resolving packages...
Couldn't find any versions for "react-native-read-more" that matches "^2.2.0"
? Please choose a version of "react-native-read-more" from this list: (Use arrow keys)
❯ 1.0.0

**Comment by fawaz-ahmed** [comment]
@fantasyado the name of this package is:
`@fawazahmed/react-native-read-more`

**Comment by fantasyado** [comment]
Thanks, I'm so careless ：）
