### ISSUE TITLE
Readmore doesnt show anything on IOS, but works fine on Android

### ISSUE THREAD

**Issue by markusmunk** [fawaz-ahmed/react-native-read-more#44]

**Comment by markusmunk** [comment]
import ReadMore from "@fawazahmed/react-native-read-more";


<ReadMore
                numberOfLines={5}
                style={styles.descriptionText}
                /* seeMoreStyle={styles.readmoreAndLessbtnStyle}
                seeLessStyle={styles.readmoreAndLessbtnStyle} */
                seeMoreText="more"
                seeLessText="less"
              >
                {item.description}
                
              </ReadMore>

**Comment by fawaz-ahmed** [comment]
@markusmunk thanks for sharing this. In order to fix this I'll need some more info:
- Your react native version
- styles.descriptionText

**Comment by fawaz-ahmed** [comment]
@markusmunk I'll be closing this issue due to no response. Also ver 2.2.2 was released. You may want to upgrade the package and try again. Incase issue persists, feel free to reopen. Thanks,
