### ISSUE TITLE
iOS seeMoreText not rendered correctly

### ISSUE THREAD

**Issue by nishanttatva** [fawaz-ahmed/react-native-read-more#45]
## Bug
Firstly, great library! Works pretty well for most use cases.
I'm facing an issue on iOS, where if I set `numberOfLines={2}`  leads to the seeMoreText being rendered incorrectly. It overlaps on the 2nd line, while the 1st line of text shows the calculated padding for seeMoreText.
Please see the attached screenshot in steps below

## Platform
* iOS

## Environment info

React native info output:

```bash
 System:
    OS: macOS 11.1
    CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
    Memory: 4.60 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.16.1/bin/yarn
    npm: 6.14.12 - ~/.nvm/versions/node/v14.16.1/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK: 14.5
    Android SDK:
      API Levels: 16, 21, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3
      System Images: android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.1 => 0.63.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 2.2.0

## Steps To Reproduce

1. Render ReadMore text as below
`<View style={{
                   width: '100%',
                   maxHeight: deviceRelativeHeight(25),
                   marginTop: 13}}>
          <ReadMore
            numberOfLines={2}
            style={{...fontStyles}}
            seeMoreText={' more'}
            seeLessText={' less'}
            seeMoreStyle={{...fontStyles}}
            seeLessStyle={{...fontStyles}}>
            {description}
         </ReadMore>
</View>`

2. See rendered text on iOS device as below
![iphone12-ios14 5](https://user-images.githubusercontent.com/66659313/142398787-340069e1-20a2-4c15-ab15-c64fdf7ff1a0.png)

## Expected behaviour

1. SeeMoreText should be rendered correctly

**Comment by nishanttatva** [comment]
@fawaz-ahmed 
Digging into the implementation, found that commenting these lines fixes the issue
https://github.com/fawaz-ahmed/react-native-read-more/blob/2f163035d2ec420d37b1d104df70b5c3ca99e072/example/src/ReadMore.js#L221-L230

Can you tell me why these lines are required for iOS platform?

**Comment by fawaz-ahmed** [comment]
@nishanttatva thanks for putting this up nicely. Really appreciate!

To explain why we have these lines that you have pointed above:
In iOS, if there are empty lines above the line of impact (which is 2nd line in your case). It automatically removes those. So I have to verify again at what position is the actual line of impact.
Explaining more:
If line 1 was having some text,
line 2 was empty
line 3 was empty
line 4 was having text and lit was also the line of impact.
Then after collapse I have to identify if whether line 4 is still the line of impact or not.
in this case it becomes line number 2.
So this piece of code is a fix for this issue.

Can you console log each of these variables and send me the logs. I shall be able to identify the issue!

**Comment by nishanttatva** [comment]
That was a quick response! :raised_hands:  @fawaz-ahmed 

> Can you console log each of these variables and send me the logs. I shall be able to identify the issue!

Which variables do you mean here?

**Comment by fawaz-ahmed** [comment]
@nishanttatva replace this
```
    // find line of impact
    let _lineOfImpact = lines[numberOfLines - 1];
    _lineOfImpact.index = numberOfLines - 1;
    if (Platform.OS === 'ios') {
      const modifiedIndex = lines.findIndex((_line, index) => {
        if (index + 1 < numberOfLines - 1) {
          return false;
        }
        return collapsedLines[numberOfLines - 1].text.includes(_line.text);
      });
      _lineOfImpact = lines[modifiedIndex];
      _lineOfImpact.index = modifiedIndex;
    }
```
with
```
    // find line of impact
    let _lineOfImpact = lines[numberOfLines - 1];
    _lineOfImpact.index = numberOfLines - 1;
    console.log('lines', lines);
    console.log('collapsedLines', collapsedLines);
    console.log('_lineOfImpact before', {..._lineOfImpact});
    if (Platform.OS === 'ios') {
      const modifiedIndex = lines.findIndex((_line, index) => {
        if (index + 1 < numberOfLines - 1) {
          return false;
        }
        return collapsedLines[numberOfLines - 1].text.includes(_line.text);
      });
      console.log('modifiedIndex', modifiedIndex);
      _lineOfImpact = lines[modifiedIndex];
      _lineOfImpact.index = modifiedIndex;
    }
    console.log('_lineOfImpact after', _lineOfImpact);
```
and send me the logs, thanks!

**Comment by nishanttatva** [comment]
@fawaz-ahmed 
Apologies, the description text is bit large. Attaching a log file below. Let me know if you need a shorter reproducible text, I'll try my best to share that soon.
[number-of-lines-error-log.txt](https://github.com/fawaz-ahmed/react-native-read-more/files/7562712/log.txt)

**Comment by fawaz-ahmed** [comment]
@nishanttatva upgrade to ver 2.2.1
