### ISSUE TITLE
Logs in Metro causing my application to crash.

### ISSUE THREAD

**Issue by JRyanSaunders** [fawaz-ahmed/react-native-read-more#49]
This read more component is outputting tonnes of logs into my metro with "padding 238.33... 65.34... 332" every few milliseconds when the content is not expanded. Once opened and I press read more - the logs stop. I believe this is what is causing my application to crash. I once left my screen open for a while with all of these logs and it came up with a warning that said "Please report: excessive number of pendin..." and I couldn't read the warning because it made my application crash. I've attached some images for context.

<img width="1149" alt="Screenshot 2021-12-19 at 23 01 08" src="https://user-images.githubusercontent.com/24939507/146694062-c27965ef-317d-4898-adf0-ed1619eff559.png">

<img width="916" alt="Screenshot 2021-12-19 at 17 26 01" src="https://user-images.githubusercontent.com/24939507/146694186-319da6c1-29c5-4891-86aa-f8b15182db7d.png">

**Comment by fawaz-ahmed** [comment]
@JRyanSaunders thanks for reporting. I'll check this out. Is there any stacktrace to this error or is it just repeating logs ?
Another question, are you rendering a list of read more component? How many if so ? Is it inside a flatlist ?
The higher issue I see here is that the logs appear to be running in a loop. If you can share some piece of code I can replicate this issue.

**Comment by fawaz-ahmed** [comment]
@JRyanSaunders I checked code and didnt found any console logs. Maybe you are using an old version. Upgrade to v2.2.2

**Comment by JRyanSaunders** [comment]
@fawaz-ahmed I updated to the latest version and it seems to have fixed it! Thanks mate :)

**Comment by fawaz-ahmed** [comment]
Super. Glad you're unblocked.
