### ISSUE TITLE
Adding support for HTML text

### ISSUE THREAD

**Issue by PopJoestar** [fawaz-ahmed/react-native-read-more#55]
Hi, thanks for this great package, I think it will be good if we add support for HTML text, currently I'm using text-clipper in my project.

**Comment by fawaz-ahmed** [comment]
Hi @PopJoestar, thanks for those kind words.

The idea seems nice. I will think around it and explore a bit. The problem arises with edge cases, like if a user clicks on a link, since its html then what should happen ? If images are there inside then how to handle those ? Or shall we have another lib with webview for react native ?
If you have some more input on dealing with these please feel free to comment.

**Comment by PopJoestar** [comment]
I thought we could improve the current renderer to support HTML by passing HTML renderers like [https://github.com/meliorence/react-native-render-html](url) through the `customTextComponent` props.

**Comment by fawaz-ahmed** [comment]
Hi @PopJoestar, with `text-clipper` it's possible to render html inside `ReadMore` component:

```
import { Dimensions } from 'react-native';
import clip from 'text-clipper';

const htmlString = `
<p style='text-align:left;padding:0;margin:0'>
  Hello World!
  Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
</p>`;

// inside your component

<ReadMore numberOfLines={3}>
  {clip(htmlString, screenWidth, {html: true, stripTags: true})}
</ReadMore

```
Thanks for pointing out to this great lib: https://github.com/arendjr/text-clipper

**Comment by PopJoestar** [comment]
Hi @fawaz-ahmed , thanks for the tips! I'm already using it in my project with react-native-render-HTML but I haven't tested it yet with your library

**Comment by fawaz-ahmed** [comment]
I've tested and shared the sample code. It works great. Thanks @
________________________________

**Comment by saad9624-tribalScale** [comment]
ITs not showing complete HTML just showing  9 lines without picking html classes

**Comment by fawaz-ahmed** [comment]
@saad9624-tribalScale can you share the response you are getting from the `clip` method.
I need to know if my lib is showing less lines or is `clip` method returning lesser text.

**Comment by saad9624-tribalScale** [comment]
Yeah, its working after adding width to undefined.

**Comment by mohil-nft** [comment]
@fawaz-ahmed I am using the library with expo, works great on mobile devices, for web I am not able to make this work.

**Comment by fawaz-ahmed** [comment]
@mohil-nft this package doesn't supports web. It depends on `Text` component from `react-native` package for applying logical updates and calculations.

**Comment by faiyyazk25** [comment]
> Hi [@PopJoestar](https://github.com/PopJoestar), with `text-clipper` it's possible to render html inside `ReadMore` component:
> 
> ```
> import { Dimensions } from 'react-native';
> import clip from 'text-clipper';
> 
> const htmlString = `
> <p style='text-align:left;padding:0;margin:0'>
>   Hello World!
>   Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
> </p>`;
> 
> // inside your component
> 
> <ReadMore numberOfLines={3}>
>   {clip(htmlString, screenWidth, {html: true, stripTags: true})}
> </ReadMore
> ```
> 
> Thanks for pointing out to this great lib: https://github.com/arendjr/text-clipper

But this will strip all the html styles

**Comment by Faiyyaz** [comment]
> Hi [@PopJoestar](https://github.com/PopJoestar), with `text-clipper` it's possible to render html inside `ReadMore` component:
> 
> ```
> import { Dimensions } from 'react-native';
> import clip from 'text-clipper';
> 
> const htmlString = `
> <p style='text-align:left;padding:0;margin:0'>
>   Hello World!
>   Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
> </p>`;
> 
> // inside your component
> 
> <ReadMore numberOfLines={3}>
>   {clip(htmlString, screenWidth, {html: true, stripTags: true})}
> </ReadMore
> ```
> 
> Thanks for pointing out to this great lib: https://github.com/arendjr/text-clipper

But this will strip all the html styles I want to preserve the styles and do the read more
