### ISSUE TITLE
Add text props support to remove See More and See Less onPress Highlighting

### ISSUE THREAD

**Issue by EdgarPetrosian** [fawaz-ahmed/react-native-read-more#58]
Please add -> suppressHighlighting ->  iOS
When true, no visual change is made when text is pressed down. By default, a gray oval highlights the text on press down.

More about this you can reed in react-native text documentation 👇
https://reactnative.dev/docs/text#suppresshighlighting-ios

**Comment by fawaz-ahmed** [comment]
Hi @EdgarPetrosian , if you pass any props to `ReadMore` component, it's passed down to the see more or less component. Please try it out:
```
<ReadMore numberOfLines={3} style={styles.textStyle} suppressHighlighting={true}>
  {
    "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
  }
</ReadMore>
```

**Comment by fawaz-ahmed** [comment]
@EdgarPetrosian can you please confirm if this issue is resolved ?

**Comment by fawaz-ahmed** [comment]
Closing issue due to no response! If issue persists feel free to re-open
