### ISSUE TITLE
"more" text alignment issue when we passed font size for more text

### ISSUE THREAD

**Issue by patidararvind** [fawaz-ahmed/react-native-read-more#62]
Please could you give solution for that issue .
Thanks 
![Simulator Screen Shot - iPhone 13 - 2022-04-21 at 06 49 16](https://user-images.githubusercontent.com/6198959/164352637-0c6c153c-2e18-4afa-a7d4-899621ad9f1c.png)

My code 
 <ReadMore
            style={[styles.text, descText]}
            numberOfLines={numberOfLineDisplay}
            seeMoreText={'more'}
            seeLessText={'less'}
            seeMoreOverlapCount={0}
            allowFontScaling={false}
            // seeMoreStyle={styles.text}
            seeLessStyle={[styles.lessText, 'less']}
            seeMoreStyle={[styles.moreText, 'more']}>
            <ParsedText
              style={[styles.text, descriptionTxt]}
              parse={[
                {pattern: tagRegex, renderText: renderTagText},
                {pattern: urlRegex, renderText: renderURLText},
              ]}
              childrenProps={{allowFontScaling: false}}>
              {descriptions}
              {/* {readMore ? descriptions : descriptions.substring(0, character)} */}
            </ParsedText>
          </ReadMore>

Style 
const styles = StyleSheet.create({
  text: {
    fontSize: 16,
    paddingVertical: '2%',
    fontFamily: fonts.RRegular,
    color: colors.lightBlackColor,
  },
  moreText: {
    color: 'gray',
    fontFamily: fonts.RRegular,
    fontSize: 12,
  },
  lessText: {
    color: 'gray',
    fontSize: 12,
  },
});

**Comment by fawaz-ahmed** [comment]
Hi @patidararvind , thanks for sharing this. The styles you are passing seem to have a text value in the array:
```
seeLessStyle={[styles.lessText, 'less']}
seeMoreStyle={[styles.moreText, 'more']}
```
Can you please remove it and test ?

Replace:
```
seeLessStyle={[styles.lessText, 'less']}
seeMoreStyle={[styles.moreText, 'more']}
```
with
```
seeLessStyle={styles.lessText}
seeMoreStyle={styles.moreText}
```

In any case I will try to reproduce this (maybe over the weekend, cannot guarantee a timeline) and post back here. If the above fix resolves the issue, then please respond in the thread. Thanks,

**Comment by fawaz-ahmed** [comment]
Closing issue due to no response.
