### ISSUE TITLE
Support optional custom function when See More pressed

### ISSUE THREAD

**Issue by ChrisLFieldsII** [fawaz-ahmed/react-native-read-more#63]
Hello,

I am using this component in a project and it works perfectly!

There is one use case I needed and had to use patch-package to add for my project, and that is the ability to use a custom function when "See More" is clicked. 

For example, when "See More" is clicked, instead of expanding text, open up a modal.

[Here](https://drive.google.com/file/d/1k-LJIp1OJ4wlNiUjKOmpipa-NzzVB7Qq/view?usp=sharing) is an example video of this functionality. 

[Here](https://drive.google.com/file/d/1T0OJWxg5vrV5Q5xsW_fV0ZuGHZ2j8i8x/view?usp=sharing) is the patch that I applied to achieve this.

I can open up a PR if you believe this is functionality that would improve the package.

Thanks.

**Comment by fawaz-ahmed** [comment]
Hi @ChrisLFieldsII I like the idea. Also I reviewed the patch file and the video. Looks like a nice addition we can have.

I'd just say the name `onToggle` isn't a best fit. It should be something like `blockedToggle` or `onSeeMoreBlocked` or something which will indicate the purpose in a better way.

Having said that a PR would be highly appreciated!!

**Comment by ChrisLFieldsII** [comment]
I agree on the naming! 

I can name it `onSeeMoreBlocked` and document that when a function is passed, this prop will disable the default See More toggling and use the custom callback instead.

I'll try to open a PR this weekend for it.

**Comment by fawaz-ahmed** [comment]
@ChrisLFieldsII wonderful.

Once you're about to raise a PR, just make sure to update these:
1_ In package.json update version `2.3.5` to `2.3.6`
2_ Update the newly added prop in readme.md

Thanks,

**Comment by fawaz-ahmed** [comment]
Thanks @ChrisLFieldsII , the feature is published. Ver 2.3.6

**Comment by ChrisLFieldsII** [comment]
Awesome!
 
Thanks for the package, saved us quite a bit of time @fawaz-ahmed
