### ISSUE TITLE
ellipsis override text content when I using seeLessText is japanese

### ISSUE THREAD

**Issue by phuocantd** [fawaz-ahmed/react-native-read-more#66]
![image](https://user-images.githubusercontent.com/31690470/170618984-50601e34-f26a-4130-ac1f-16df3f9e739f.png)

**Comment by fawaz-ahmed** [comment]
Hi @phuocantd , thanks for posting this bug. Can you also paste the text here ? it will help me fix the issue.

**Comment by phuocantd** [comment]
> Hi @phuocantd , thanks for posting this bug. Can you also paste the text here ? it will help me fix the issue.

Sorry for to late, text is `続きを読む`

**Comment by fawaz-ahmed** [comment]
Hi @phuocantd , tried with your text. I wasn't able to reproduce. Can you share the
1_ complete text ?
2_ your simulator/device ? android or ios
3_ your device's language ? (in device settings)
<img width="836" alt="Screen Shot 2022-05-31 at 3 25 25 PM" src="https://user-images.githubusercontent.com/17975968/171152849-83754b24-a631-4d08-ad91-6cb901bb41ac.png">

**Comment by fawaz-ahmed** [comment]
@phuocantd update, after posting this image I noticed an overlap in iOS.

Use prop: `seeMoreOverlapCount={5}`

You can increase the value to 5 or higher. Default is 2.

**Comment by phuocantd** [comment]
> @phuocantd update, after posting this image I noticed an overlap in iOS.
> 
> Use prop: `seeMoreOverlapCount={5}`
> 
> You can increase the value to 5 or higher. Default is 2.

using `seeMoreOverlapCount` fixed for me. Thank you
