### ISSUE TITLE
Border line attributes Not applicable on seeLessStyle.

### ISSUE THREAD

**Issue by amang-dew** [fawaz-ahmed/react-native-read-more#67]
seeLessStyle: {
    fontFamily: FONT_FAMILY.OpenSansRegular,
    fontSize: normalize(14),
    color:colors.inactiveTabColor,
    borderBottomWidth:1,
    borderColor:colors.activeButtonColor
  }

<ReadMore style={styles.caption}
                seeMoreText={'See More'}
                seeMoreStyle={styles.seeMoreStyle}
                seeLessText={'See Less'}
                seeLessStyle={styles.seeLessStyle}
                numberOfLines={3}
              >{item.postData}
</ReadMore>

Border is not visible on See Less Text.
@fawaz-ahmed

**Comment by fawaz-ahmed** [comment]
@amang-dew border will not appear in `see less` since it's a nested text component. You can use the underline css:
```
seeLessStyle: {
  fontFamily: FONT_FAMILY.OpenSansRegular,
  fontSize: normalize(14),
  color:colors.inactiveTabColor,
  textDecorationLine: 'underline'
}
```

**Comment by amang-dew** [comment]
Thanks @fawaz-ahmed. It works for me.
