### ISSUE TITLE
after using this library all my screen has animation 

### ISSUE THREAD

**Issue by hotaryuzaki** [fawaz-ahmed/react-native-read-more#71]
it's weird issue, after using this package in one of my screen then suddenly all my screen has animation.
example:
- smooth animation fade in and fade out transition
- in cart screen i have delete product function, when the product deleted from the state layout has bouncing animation transition.
- bouncing animation when user sliding up the bottom sheet

when i remove the import script of this package, all the animation is gone.

**Comment by hotaryuzaki** [comment]
i think this is the problem

```
if (Platform.OS === 'android') {
  if (UIManager.setLayoutAnimationEnabledExperimental) {
    UIManager.setLayoutAnimationEnabledExperimental(true);
  }
}
```

this feature create bugs,
- some modal doesn't have overlay background
- in cart screen product list container height not change, in the beginning i have 3 products and i delete 2 products so the list product container showing empty space after product deleted

**Comment by fawaz-ahmed** [comment]
@hotaryuzaki you can disable animation by passing `animate={false}`

**Comment by hotaryuzaki** [comment]
> @hotaryuzaki you can disable animation by passing `animate={false}`

read more animation is disable but the problem still exist

it solves when i change to this
```
if (Platform.OS === 'android') {
  if (UIManager.setLayoutAnimationEnabledExperimental) {
    UIManager.setLayoutAnimationEnabledExperimental(false);
  }
}
```

**Comment by fawaz-ahmed** [comment]
@hotaryuzaki I will remove this piece of code from my lib to enable layout animation, since that should be handled by the app itself. Will raise a PR soon.
