### ISSUE TITLE
line spacing in a paragraph

### ISSUE THREAD

**Issue by darias08** [fawaz-ahmed/react-native-read-more#72]
Hi I am trying to create the amount of spacing in a paragraph between top line and below line.

Ex:
ffffffff
            <--- The amount of space I can place.
ffffffff

I have tried numberOfLines which just makes how many lines you want in your paragraph and not necessarily the amount of spacing in-between the paragraphs.

**Comment by fawaz-ahmed** [comment]
Hi @darias08 , this is a styling issue, you need to adjust the style property `lineHeight`
ref: https://reactnative.dev/docs/text-style-props#lineheight

The ReadMore component is using Text component and any Text prop you pass down will reflect similar to a Text component.
