### ISSUE TITLE
are you using TextPropTypes? because it's deprecated by React Native

### ISSUE THREAD

**Issue by hotaryuzaki** [fawaz-ahmed/react-native-read-more#74]
it is a question,
are you using TextPropTypes?
it's deprecated by React Native and will rise an error
```Invariant Violation: ViewPropTypes has been removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types'```

**Comment by fawaz-ahmed** [comment]
I will check this one. Thanks for raising this issue.

**Comment by fawaz-ahmed** [comment]
@hotaryuzaki I tested with both js and ts. I didn't saw any violations. Although `TextPropTypes` is being used. Can you help me reproduce this issue ? or provide a way of reproducing this warning.

**Comment by hotaryuzaki** [comment]
> @hotaryuzaki I tested with both js and ts. I didn't saw any violations. Although `TextPropTypes` is being used. Can you help me reproduce this issue ? or provide a way of reproducing this warning.

what RN version are you using?
try using RN 0.70.5

**Comment by fawaz-ahmed** [comment]
@hotaryuzaki tried with rn version 0.70.5 and 0.70.6. It worked fine. But in any case I will remove ref for TextPropTypes since it's deprecated
