### ISSUE TITLE
Not working with react-native-web

### ISSUE THREAD

**Issue by eliarc** [fawaz-ahmed/react-native-read-more#79]
Demo: https://www.loom.com/share/11f40ee1bda84aa886c5f92699e55eec

**Comment by fawaz-ahmed** [comment]
Hi @eliarc , this library will work only for android and ios. It wont work on web, reason being it depends on `onTextLayout` and `onLayout` callback props from Text component.

**Comment by eliarc** [comment]
@fawaz-ahmed got it, thanks for the reply 🙏
