### ISSUE TITLE
This library is not working in web

### ISSUE THREAD

**Issue by Aayushsctib** [fawaz-ahmed/react-native-read-more#80]
When using this library in web the text is truncating but `see more` button is not visible

**Comment by fawaz-ahmed** [comment]
> When using this library in web the text is truncating but `see more` button is not visible

This library is not compatible with web. It depends on `onLayout` and `onTextLayout` callbacks from `Text` component in react native to measure and identify `see more` placement.

**Comment by fawaz-ahmed** [comment]
Duplicate https://github.com/fawaz-ahmed/react-native-read-more/issues/79
