### ISSUE TITLE
rendering see more text in a new line

### ISSUE THREAD

**Issue by Bayramito** [fawaz-ahmed/react-native-read-more#82]
<img width="393" alt="Ekran Resmi 2023-10-04 15 57 12" src="https://github.com/fawaz-ahmed/react-native-read-more/assets/44513402/3bcd6a97-c911-41ca-bde0-3fe45e2d588e">

As you can see here,  see more text is being added next to the actual text.
What if I want to render it in a new line?

NOTE: i found a way to do that by adding `width: 100%`  to the  `seeMoreContainerStyleSecondary` prop but
could not use same for see less..

**Comment by fawaz-ahmed** [comment]
Hi @Bayramito , if you want read more in the next line, you can switch to a different library:
https://www.npmjs.com/package/react-native-read-more-text
